#!/bin/bash

# Colors
BLACK="\e[30m"
RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
BLUE="\e[34m"
MAGENTA="\e[35m"
CYAN="\e[36m"
GREY="\e[37m"
RESET="\e[0m"

echo -e "${BLUE}=== Configs files ===${RESET}"
cat <<EOF
zshrc	-> n ${HOME}/.zshrc
hypr	-> n ${HOME}/.config/hypr/hyprland.conf
lock	-> n ${HOME}/.config/hypr/hyprlock.conf
idle	-> n ${HOME}/.config/hypr/hypridle.conf
bar	-> n ${HOME}/.config/waybar/config.jsonc
notif	-> n ${HOME}/.config/mako/config
custom-launcher -> n ${HOME}/.config/hypr/scripts/rofi-file-manager.sh
wall	-> ${HOME}/.config/hypr/scripts/random_wallpaper.sh
help	-> ${HOME}/help.sh
EOF
