#!/bin/bash

# Colors
BLACK="\e[30m"
RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
BLUE="\e[34m"
MAGENTA="\e[35m"
CYAN="\e[36m"
GREY="\e[37m"
RESET="\e[0m"

echo -e "${YELLOW}=== ~/.config/hypr/scripts/help/help-wifi ===${RESET}"
echo -e "${BLUE}=== NetworkManager (TUI) ===${RESET}"
cat <<EOF
nmcli general status	-> Display general status
nmcli device status	-> List network interfaces
nmcli device wifi list	-> List available network
nmcli device wifi connect <SSID> password <pwd> -> Connect to a network
nmcli connection show	-> Display configured networks
nmcli connection modify <wifi> connection.autoconnect yes -> Autoconnect wifi
EOF

echo -e "${BLUE}===  (ITUI) ===${RESET}"
cat <<EOF
nmtui			-> Start ITUI interface
EOF

echo -e "${BLUE}=== nm-connection-editor (GUI) ===${RESET}"
cat <<EOF
nm-connection-editor	-> Start GUI interface
EOF
