#!/bin/bash

# Colors
BLACK="\e[30m"
RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
BLUE="\e[34m"
MAGENTA="\e[35m"
CYAN="\e[36m"
GREY="\e[37m"
RESET="\e[0m"

echo -e "${YELLOW}=== ~/.config/hypr/scripts/help/help-battery ===${RESET}"
echo -e "${BLUE}=== Battery Status ===${RESET}"
cat <<EOF
upower -e		-> Display all power devices
upower -i <upower -e>	-> Detailed battery info
acpi			-> Battery status with percentage
EOF
