#!/bin/bash

# Colors
BLACK="\e[30m"
RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
BLUE="\e[34m"
MAGENTA="\e[35m"
CYAN="\e[36m"
GREY="\e[37m"
RESET="\e[0m"

echo -e "${BLUE}=== Vim ===${RESET}"
cat <<EOF
n, v, vi, vim -> nvim
EOF

echo -e "${BLUE}=== Terminal ===${RESET}"
cat <<EOF
ll	-> la -Alh
ls	-> lsd --group-dirs first
fibo	-> ${HOME}/.config/waybar/scripts/fibo.sh
cursor	-> find /usr/share/icons ${HOME}/.local/share/icons ${HOME}/.icons -type d -name "cursors"
display	-> nwg-look
EOF

echo -e "${BLUE}=== Holberton (C/Valgrind) ===${RESET}"
cat <<EOF
gcch	-> gcc -Wall -pedantic -Werror -Wextra -std=gnu89
val	-> clear && valgrind --leak-check=full --track-origins=yes --show-leak-kinds=all ./a.out
EOF

echo -e "${BLUE}=== Love2D ===${RESET}"
cat <<EOF
lov	-> love ./
EOF

echo -e "${BLUE}=== Fastfetch ===${RESET}"
cat <<EOF
ff	-> fastfetch
ffm	-> fastfetch --config ${HOME}/.config/fastfetch/start.jsonc
EOF
